<!--<footer class="footer" style="height: 8%;max-height: 8%;position:">
    
        <div class="btn-group btn-group-lg" role="group" aria-label="Botones" style="width: 100% !important;">
            <button id="btn_atras" type="button" class="btn azul-btn btn-block" style="margin-top: 0 !important;" contador="0" disabled>Atras</button>
            <button id="btn_continuar" type="button" class="btn azul-btn btn-block" style="margin-top: 0 !important;" contador="1" disabled>Continuar</button>

        </div>
    
</footer>-->
<input type="hidden" id="url" value="<?php echo PUBLIC_PATH; ?>" >